#!/usr/bin/env python3
"""
Generate data/seeds/vietnamese_recipes.json for Cravvy Cooking App.

Aligned with project report:
- Urban youth 18–30, eat clean / fitness, low-effort UX
- AI meal plan + swap + auto calorie tracking
- Simple recipes (mostly <= 30–40 min), not a "super health app" but healthier choices

Tags match app filters (setup_screen diets + meal_suggester goals):
  Eat Clean, Low-Carb, Keto, Vegetarian, Vegan, High-Protein, Low-Sugar, Gluten-Free
  + low carb, high protein (goal scoring)
  + quick (prep_time <= 20, cooking_time filter)
  + allergen hints: seafood, pork, beef, egg, peanut, shellfish, gluten, dairy

Run: python tools/generate_vn_seed.py
"""

from __future__ import annotations

import json
import re
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "seeds" / "vietnamese_recipes.json"
SOURCE = "cravvy_curated_vn"

# Each entry:
# name, meal_type, calories, protein, carbs, fat, prep_time, difficulty,
# tags (explicit), ingredients (short list for steps/description)
#
# meal_type: breakfast | lunch | dinner | snack
DISHES: list[dict] = [
    # ── Breakfast (25): nhanh, bữa sáng lành mạnh ──
    {
        "name": "Phở gà nạc",
        "meal_type": "breakfast",
        "calories": 360,
        "protein": 28,
        "carbs": 42,
        "fat": 8,
        "prep_time": 30,
        "difficulty": "medium",
        "tags": ["vietnamese", "eat clean", "high protein", "chicken"],
        "ingredients": ["ức gà", "bánh phở", "hành lá", "gừng", "rau thơm"],
    },
    {
        "name": "Phở chay rau củ",
        "meal_type": "breakfast",
        "calories": 300,
        "protein": 12,
        "carbs": 48,
        "fat": 6,
        "prep_time": 25,
        "difficulty": "easy",
        "tags": ["vietnamese", "vegetarian", "vegan", "eat clean"],
        "ingredients": ["bánh phở", "đậu phụ", "nấm", "cà rốt", "ngò"],
    },
    {
        "name": "Cháo gà gạo lứt",
        "meal_type": "breakfast",
        "calories": 280,
        "protein": 22,
        "carbs": 36,
        "fat": 6,
        "prep_time": 25,
        "difficulty": "easy",
        "tags": ["vietnamese", "eat clean", "high protein", "gluten-free", "chicken"],
        "ingredients": ["gạo lứt", "ức gà", "gừng", "hành lá"],
    },
    {
        "name": "Cháo yến mạch trứng",
        "meal_type": "breakfast",
        "calories": 320,
        "protein": 18,
        "carbs": 38,
        "fat": 10,
        "prep_time": 15,
        "difficulty": "easy",
        "tags": ["eat clean", "high protein", "quick", "egg"],
        "ingredients": ["yến mạch", "trứng gà", "sữa ít béo", "chuối"],
    },
    {
        "name": "Bánh mì trứng ốp la ",
        "meal_type": "breakfast",
        "calories": 340,
        "protein": 16,
        "carbs": 36,
        "fat": 14,
        "prep_time": 12,
        "difficulty": "easy",
        "tags": ["vietnamese", "eat clean", "quick", "egg", "gluten"],
        "ingredients": ["bánh mì nguyên cám", "trứng", "rau xà lách", "cà chua"],
    },
    {
        "name": "Bánh mì gà nướng",
        "meal_type": "breakfast",
        "calories": 360,
        "protein": 24,
        "carbs": 38,
        "fat": 12,
        "prep_time": 15,
        "difficulty": "easy",
        "tags": ["vietnamese", "eat clean", "high protein", "quick", "chicken", "gluten"],
        "ingredients": ["bánh mì", "ức gà nướng", "dưa leo", "rau"],
    },
    {
        "name": "Bánh cuốn chay",
        "meal_type": "breakfast",
        "calories": 260,
        "protein": 10,
        "carbs": 44,
        "fat": 6,
        "prep_time": 25,
        "difficulty": "medium",
        "tags": ["vietnamese", "vegetarian", "eat clean", "low carb"],
        "ingredients": ["bột gạo", "nấm", "đậu xanh", "hành phi"],
    },
    {
        "name": "Xôi gấc ít đường",
        "meal_type": "breakfast",
        "calories": 300,
        "protein": 8,
        "carbs": 58,
        "fat": 5,
        "prep_time": 20,
        "difficulty": "easy",
        "tags": ["vietnamese", "vegetarian", "low sugar"],
        "ingredients": ["gạo nếp", "gấc", "đậu xanh", "muối"],
    },
    {
        "name": "Sữa chua granola trái cây",
        "meal_type": "breakfast",
        "calories": 280,
        "protein": 14,
        "carbs": 36,
        "fat": 8,
        "prep_time": 5,
        "difficulty": "easy",
        "tags": ["eat clean", "quick", "low sugar", "dairy"],
        "ingredients": ["sữa chua không đường", "granola", "dâu", "chuối"],
    },
    {
        "name": "Smoothie xanh táo bơ",
        "meal_type": "breakfast",
        "calories": 260,
        "protein": 8,
        "carbs": 28,
        "fat": 14,
        "prep_time": 5,
        "difficulty": "easy",
        "tags": ["eat clean", "vegan", "quick", "low sugar", "keto"],
        "ingredients": ["bơ", "táo", "rau bina", "nước dừa"],
    },
    {
        "name": "Trứng luộc + bánh mì đen",
        "meal_type": "breakfast",
        "calories": 300,
        "protein": 18,
        "carbs": 28,
        "fat": 12,
        "prep_time": 12,
        "difficulty": "easy",
        "tags": ["eat clean", "high protein", "quick", "egg", "gluten"],
        "ingredients": ["trứng gà", "bánh mì đen", "bơ lạt"],
    },
    {
        "name": "Ức gà áp chảo rau củ",
        "meal_type": "breakfast",
        "calories": 320,
        "protein": 36,
        "carbs": 14,
        "fat": 12,
        "prep_time": 18,
        "difficulty": "easy",
        "tags": ["eat clean", "high protein", "low carb", "quick", "chicken"],
        "ingredients": ["ức gà", "bông cải", "cà rốt", "tỏi"],
    },
    {
        "name": "Bún gà sốt me ít dầu",
        "meal_type": "breakfast",
        "calories": 380,
        "protein": 26,
        "carbs": 48,
        "fat": 10,
        "prep_time": 25,
        "difficulty": "medium",
        "tags": ["vietnamese", "eat clean", "high protein", "chicken"],
        "ingredients": ["bún", "gà luộc", "me", "rau sống", "đậu phộng"],
    },
    {
        "name": "Hủ tiếu Nam Vang rau",
        "meal_type": "breakfast",
        "calories": 360,
        "protein": 20,
        "carbs": 50,
        "fat": 10,
        "prep_time": 30,
        "difficulty": "medium",
        "tags": ["vietnamese", "eat clean", "pork"],
        "ingredients": ["hủ tiếu", "thịt heo nạc", "tôm", "giá", "hành"],
    },
    {
        "name": "Mì Quảng gà",
        "meal_type": "breakfast",
        "calories": 400,
        "protein": 24,
        "carbs": 52,
        "fat": 12,
        "prep_time": 30,
        "difficulty": "medium",
        "tags": ["vietnamese", "eat clean", "chicken"],
        "ingredients": ["mì Quảng", "gà", "trứng cút", "rau sống"],
    },
    {
        "name": "Cháo cá hồi",
        "meal_type": "breakfast",
        "calories": 290,
        "protein": 24,
        "carbs": 34,
        "fat": 8,
        "prep_time": 25,
        "difficulty": "easy",
        "tags": ["eat clean", "high protein", "seafood", "gluten-free"],
        "ingredients": ["gạo", "cá hồi", "gừng", "hành lá"],
    },
    {
        "name": "Bánh mì trứng rau",
        "meal_type": "breakfast",
        "calories": 310,
        "protein": 14,
        "carbs": 36,
        "fat": 12,
        "prep_time": 10,
        "difficulty": "easy",
        "tags": ["vietnamese", "quick", "egg", "gluten"],
        "ingredients": ["bánh mì", "trứng", "dưa leo", "ngò"],
    },
    {
        "name": "Đậu hũ sốt cà breakfast bowl",
        "meal_type": "breakfast",
        "calories": 260,
        "protein": 18,
        "carbs": 20,
        "fat": 12,
        "prep_time": 15,
        "difficulty": "easy",
        "tags": ["vegetarian", "vegan", "eat clean", "quick", "low carb"],
        "ingredients": ["đậu hũ", "cà chua", "nấm", "hành tây"],
    },
    {
        "name": "Yogurt parfait đào",
        "meal_type": "breakfast",
        "calories": 240,
        "protein": 12,
        "carbs": 32,
        "fat": 6,
        "prep_time": 5,
        "difficulty": "easy",
        "tags": ["eat clean", "quick", "low sugar", "dairy"],
        "ingredients": ["sữa chua Hy Lạp", "đào", "hạt chia"],
    },
    {
        "name": "Bún chả nướng ít mỡ",
        "meal_type": "breakfast",
        "calories": 420,
        "protein": 28,
        "carbs": 46,
        "fat": 14,
        "prep_time": 35,
        "difficulty": "medium",
        "tags": ["vietnamese", "high protein", "pork"],
        "ingredients": ["bún", "thịt heo nạc nướng", "dưa góp", "rau thơm"],
    },
    {
        "name": "Súp bí đỏ kem nhạt",
        "meal_type": "breakfast",
        "calories": 180,
        "protein": 6,
        "carbs": 24,
        "fat": 6,
        "prep_time": 20,
        "difficulty": "easy",
        "tags": ["vegetarian", "eat clean", "low carb", "quick"],
        "ingredients": ["bí đỏ", "sữa ít béo", "hành tây"],
    },
    {
        "name": "Phở bò nạc",
        "meal_type": "breakfast",
        "calories": 400,
        "protein": 30,
        "carbs": 46,
        "fat": 12,
        "prep_time": 40,
        "difficulty": "medium",
        "tags": ["vietnamese", "high protein", "beef"],
        "ingredients": ["thịt bò nạc", "bánh phở", "xương hầm", "rau thơm"],
    },
    {
        "name": "Bánh bao chay nấm",
        "meal_type": "breakfast",
        "calories": 280,
        "protein": 10,
        "carbs": 48,
        "fat": 6,
        "prep_time": 20,
        "difficulty": "easy",
        "tags": ["vegetarian", "eat clean"],
        "ingredients": ["bột mì", "nấm hương", "đậu phụ"],
    },
    {
        "name": "Cơm gạo lứt trứng chiên ít dầu",
        "meal_type": "breakfast",
        "calories": 350,
        "protein": 16,
        "carbs": 48,
        "fat": 10,
        "prep_time": 15,
        "difficulty": "easy",
        "tags": ["eat clean", "quick", "egg", "gluten-free"],
        "ingredients": ["gạo lứt", "trứng", "cà rốt", "đậu Hà Lan"],
    },
    {
        "name": "Sinh tố chuối đậu phộng",
        "meal_type": "breakfast",
        "calories": 300,
        "protein": 12,
        "carbs": 38,
        "fat": 12,
        "prep_time": 5,
        "difficulty": "easy",
        "tags": ["eat clean", "high protein", "quick", "peanut"],
        "ingredients": ["chuối", "đậu phộng", "sữa hạnh nhân"],
    },
    # ── Lunch (35): cơm/bún/gỏi cân bằng, meal prep friendly ──
    {
        "name": "Gỏi cuốn tôm gạo lứt",
        "meal_type": "lunch",
        "calories": 280,
        "protein": 22,
        "carbs": 32,
        "fat": 8,
        "prep_time": 20,
        "difficulty": "easy",
        "tags": ["vietnamese", "eat clean", "low carb", "seafood", "shellfish"],
        "ingredients": ["tôm", "bánh tráng", "bún", "rau sống", "bạc hà"],
    },
    {
        "name": "Gỏi gà bắp cải",
        "meal_type": "lunch",
        "calories": 260,
        "protein": 28,
        "carbs": 18,
        "fat": 8,
        "prep_time": 15,
        "difficulty": "easy",
        "tags": ["eat clean", "high protein", "low carb", "quick", "chicken"],
        "ingredients": ["ức gà", "bắp cải", "cà rốt", "đậu phộng"],
    },
    {
        "name": "Gỏi đu đủ tôm",
        "meal_type": "lunch",
        "calories": 240,
        "protein": 20,
        "carbs": 22,
        "fat": 8,
        "prep_time": 15,
        "difficulty": "easy",
        "tags": ["vietnamese", "eat clean", "low carb", "seafood"],
        "ingredients": ["đu đủ xanh", "tôm luộc", "rau thơm", "me"],
    },
    {
        "name": "Cơm gạo lứt gà nướng",
        "meal_type": "lunch",
        "calories": 480,
        "protein": 38,
        "carbs": 52,
        "fat": 12,
        "prep_time": 30,
        "difficulty": "medium",
        "tags": ["eat clean", "high protein", "gluten-free", "chicken"],
        "ingredients": ["gạo lứt", "đùi gà bỏ da", "rau luộc"],
    },
    {
        "name": "Cơm tấm sườn nướng (phần fit)",
        "meal_type": "lunch",
        "calories": 520,
        "protein": 32,
        "carbs": 58,
        "fat": 16,
        "prep_time": 25,
        "difficulty": "easy",
        "tags": ["vietnamese", "high protein", "pork"],
        "ingredients": ["sườn heo nạc", "gạo tấm", "dưa leo", "đồ chua"],
    },
    {
        "name": "Cơm rang dưa bò ít dầu",
        "meal_type": "lunch",
        "calories": 460,
        "protein": 28,
        "carbs": 54,
        "fat": 14,
        "prep_time": 18,
        "difficulty": "easy",
        "tags": ["vietnamese", "high protein", "quick", "beef"],
        "ingredients": ["thịt bò", "cơm nguội", "dưa chuột", "trứng"],
    },
    {
        "name": "Cơm chiên rau củ trứng",
        "meal_type": "lunch",
        "calories": 380,
        "protein": 14,
        "carbs": 58,
        "fat": 10,
        "prep_time": 15,
        "difficulty": "easy",
        "tags": ["vegetarian", "eat clean", "quick", "egg"],
        "ingredients": ["cơm", "trứng", "đậu Hà Lan", "cà rốt"],
    },
    {
        "name": "Cơm chay đậu hũ sốt cà",
        "meal_type": "lunch",
        "calories": 360,
        "protein": 18,
        "carbs": 48,
        "fat": 12,
        "prep_time": 20,
        "difficulty": "easy",
        "tags": ["vegetarian", "vegan", "eat clean"],
        "ingredients": ["gạo", "đậu hũ", "cà chua", "nấm"],
    },
    {
        "name": "Cơm cá hồi sốt teriyaki nhạt",
        "meal_type": "lunch",
        "calories": 440,
        "protein": 34,
        "carbs": 42,
        "fat": 14,
        "prep_time": 25,
        "difficulty": "medium",
        "tags": ["eat clean", "high protein", "seafood", "gluten-free"],
        "ingredients": ["cá hồi", "gạo", "bông cải", "tương ít muối"],
    },
    {
        "name": "Cơm bò lúc lắc",
        "meal_type": "lunch",
        "calories": 500,
        "protein": 36,
        "carbs": 48,
        "fat": 18,
        "prep_time": 22,
        "difficulty": "medium",
        "tags": ["vietnamese", "high protein", "beef"],
        "ingredients": ["thịt bò", "cơm", "cà chua", "dưa leo"],
    },
    {
        "name": "Bún thịt nướng chảo",
        "meal_type": "lunch",
        "calories": 420,
        "protein": 28,
        "carbs": 50,
        "fat": 12,
        "prep_time": 22,
        "difficulty": "easy",
        "tags": ["vietnamese", "eat clean", "high protein", "pork"],
        "ingredients": ["bún", "thịt heo nạc", "dưa góp", "rau"],
    },
    {
        "name": "Bún cá chua cay nhẹ",
        "meal_type": "lunch",
        "calories": 360,
        "protein": 26,
        "carbs": 44,
        "fat": 8,
        "prep_time": 28,
        "difficulty": "medium",
        "tags": ["vietnamese", "eat clean", "seafood"],
        "ingredients": ["cá phi lê", "bún", "cà chua", "thì là"],
    },
    {
        "name": "Mì xào bò rau củ",
        "meal_type": "lunch",
        "calories": 480,
        "protein": 30,
        "carbs": 52,
        "fat": 16,
        "prep_time": 18,
        "difficulty": "easy",
        "tags": ["vietnamese", "high protein", "quick", "beef", "gluten"],
        "ingredients": ["mì trứng", "thịt bò", "bắp cải", "cà rốt"],
    },
    {
        "name": "Mì hoành thánh nhạt mặn",
        "meal_type": "lunch",
        "calories": 400,
        "protein": 22,
        "carbs": 48,
        "fat": 12,
        "prep_time": 25,
        "difficulty": "medium",
        "tags": ["vietnamese", "pork", "gluten"],
        "ingredients": ["mì", "hoành thánh", "rau cải", "hành"],
    },
    {
        "name": "Salad quinoa gà nướng",
        "meal_type": "lunch",
        "calories": 380,
        "protein": 34,
        "carbs": 32,
        "fat": 12,
        "prep_time": 20,
        "difficulty": "easy",
        "tags": ["eat clean", "high protein", "low carb", "gluten-free", "chicken"],
        "ingredients": ["quinoa", "gà nướng", "xà lách", "dầu olive"],
    },
    {
        "name": "Bowl ức gà sốt yogurt",
        "meal_type": "lunch",
        "calories": 360,
        "protein": 38,
        "carbs": 28,
        "fat": 10,
        "prep_time": 18,
        "difficulty": "easy",
        "tags": ["eat clean", "high protein", "low carb", "quick", "chicken", "dairy"],
        "ingredients": ["ức gà", "khoai lang", "bông cải", "sữa chua"],
    },
    {
        "name": "Canh chua cá nhẹ",
        "meal_type": "lunch",
        "calories": 260,
        "protein": 24,
        "carbs": 18,
        "fat": 8,
        "prep_time": 25,
        "difficulty": "medium",
        "tags": ["vietnamese", "eat clean", "low carb", "seafood"],
        "ingredients": ["cá basa", "cà chua", "dứa", "đậu bắp"],
    },
    {
        "name": "Canh bí đỏ thịt bằm nạc",
        "meal_type": "lunch",
        "calories": 220,
        "protein": 18,
        "carbs": 16,
        "fat": 10,
        "prep_time": 25,
        "difficulty": "easy",
        "tags": ["vietnamese", "eat clean", "pork"],
        "ingredients": ["bí đỏ", "thịt heo bằm nạc", "hành"],
    },
    {
        "name": "Rau muống xào tỏi",
        "meal_type": "lunch",
        "calories": 120,
        "protein": 4,
        "carbs": 14,
        "fat": 6,
        "prep_time": 10,
        "difficulty": "easy",
        "tags": ["vegetarian", "vegan", "eat clean", "quick", "low carb"],
        "ingredients": ["rau muống", "tỏi", "dầu olive"],
    },
    {
        "name": "Đậu phụ sốt cà",
        "meal_type": "lunch",
        "calories": 240,
        "protein": 16,
        "carbs": 18,
        "fat": 12,
        "prep_time": 15,
        "difficulty": "easy",
        "tags": ["vegetarian", "vegan", "eat clean", "quick"],
        "ingredients": ["đậu phụ", "cà chua", "hành"],
    },
    {
        "name": "Cá kho tộ ít đường",
        "meal_type": "lunch",
        "calories": 340,
        "protein": 32,
        "carbs": 14,
        "fat": 16,
        "prep_time": 35,
        "difficulty": "medium",
        "tags": ["vietnamese", "high protein", "low carb", "seafood"],
        "ingredients": ["cá lóc", "nước mắm", "ớt", "gừng"],
    },
    {
        "name": "Tôm rim nhẹ",
        "meal_type": "lunch",
        "calories": 280,
        "protein": 30,
        "carbs": 12,
        "fat": 12,
        "prep_time": 20,
        "difficulty": "easy",
        "tags": ["vietnamese", "high protein", "low carb", "seafood", "shellfish"],
        "ingredients": ["tôm", "nước mắm", "ớt", "tiêu"],
    },
    {
        "name": "Nem nướng cuốn rau",
        "meal_type": "lunch",
        "calories": 400,
        "protein": 26,
        "carbs": 32,
        "fat": 18,
        "prep_time": 28,
        "difficulty": "medium",
        "tags": ["vietnamese", "high protein", "pork"],
        "ingredients": ["nem nướng", "bánh tráng", "bún", "rau sống"],
    },
    {
        "name": "Bún đậu chay sốt tương",
        "meal_type": "lunch",
        "calories": 380,
        "protein": 20,
        "carbs": 36,
        "fat": 16,
        "prep_time": 18,
        "difficulty": "easy",
        "tags": ["vegetarian", "eat clean", "quick"],
        "ingredients": ["đậu phụ", "bún", "dưa leo", "rau thơm"],
    },
    {
        "name": "Cơm niêu gà luộc",
        "meal_type": "lunch",
        "calories": 480,
        "protein": 36,
        "carbs": 50,
        "fat": 12,
        "prep_time": 30,
        "difficulty": "medium",
        "tags": ["vietnamese", "high protein", "chicken", "gluten-free"],
        "ingredients": ["gà ta", "gạo", "muối", "gừng"],
    },
    {
        "name": "Salad cá ngừ light",
        "meal_type": "lunch",
        "calories": 300,
        "protein": 32,
        "carbs": 16,
        "fat": 12,
        "prep_time": 12,
        "difficulty": "easy",
        "tags": ["eat clean", "high protein", "low carb", "quick", "seafood"],
        "ingredients": ["cá ngừ hộp in water", "xà lách", "cà chua", "dầu olive"],
    },
    {
        "name": "Bánh xèo rau củ",
        "meal_type": "lunch",
        "calories": 360,
        "protein": 14,
        "carbs": 42,
        "fat": 14,
        "prep_time": 25,
        "difficulty": "medium",
        "tags": ["vietnamese", "vegetarian"],
        "ingredients": ["bột gạo", "giá", "nấm", "rau sống"],
    },
    {
        "name": "Súp nấm kem nhạt",
        "meal_type": "lunch",
        "calories": 200,
        "protein": 8,
        "carbs": 18,
        "fat": 10,
        "prep_time": 20,
        "difficulty": "easy",
        "tags": ["vegetarian", "eat clean", "low carb", "dairy"],
        "ingredients": ["nấm button", "kem ít béo", "hành tây"],
    },
    {
        "name": "Cơm gà xối mỡ (phần vừa)",
        "meal_type": "lunch",
        "calories": 520,
        "protein": 34,
        "carbs": 54,
        "fat": 16,
        "prep_time": 28,
        "difficulty": "medium",
        "tags": ["vietnamese", "high protein", "chicken"],
        "ingredients": ["gà luộc", "cơm", "nước tương", "gừng"],
    },
    {
        "name": "Bún riêu đậu (chay protein)",
        "meal_type": "lunch",
        "calories": 340,
        "protein": 18,
        "carbs": 48,
        "fat": 10,
        "prep_time": 30,
        "difficulty": "medium",
        "tags": ["vegetarian", "eat clean"],
        "ingredients": ["bún", "đậu hũ", "cà chua", "rau thơm"],
    },
    {
        "name": "Gà xào sả ớt",
        "meal_type": "lunch",
        "calories": 360,
        "protein": 34,
        "carbs": 12,
        "fat": 18,
        "prep_time": 20,
        "difficulty": "easy",
        "tags": ["vietnamese", "high protein", "low carb", "keto", "chicken"],
        "ingredients": ["đùi gà phi lê", "sả", "ớt", "nấm"],
    },
    {
        "name": "Cơm thịt kho trứng (ít mỡ)",
        "meal_type": "lunch",
        "calories": 460,
        "protein": 26,
        "carbs": 48,
        "fat": 18,
        "prep_time": 40,
        "difficulty": "medium",
        "tags": ["vietnamese", "pork", "egg"],
        "ingredients": ["thịt ba chỉ cắt mỏng", "trứng", "nước dừa"],
    },
    {
        "name": "Hủ tiếu bò kho",
        "meal_type": "lunch",
        "calories": 440,
        "protein": 30,
        "carbs": 46,
        "fat": 14,
        "prep_time": 40,
        "difficulty": "medium",
        "tags": ["vietnamese", "high protein", "beef"],
        "ingredients": ["thịt bò", "hủ tiếu", "cà rốt", "hành tây"],
    },
    {
        "name": "Poke bowl cá hồi",
        "meal_type": "lunch",
        "calories": 420,
        "protein": 32,
        "carbs": 38,
        "fat": 16,
        "prep_time": 15,
        "difficulty": "easy",
        "tags": ["eat clean", "high protein", "quick", "seafood", "gluten-free"],
        "ingredients": ["cá hồi", "gạo", "edamame", "dưa leo"],
    },
    # ── Dinner (30): nhẹ hơn trưa, nhiều protein + rau ──
    {
        "name": "Gà nướng mật ong",
        "meal_type": "dinner",
        "calories": 420,
        "protein": 38,
        "carbs": 28,
        "fat": 16,
        "prep_time": 35,
        "difficulty": "medium",
        "tags": ["eat clean", "high protein", "low sugar", "chicken"],
        "ingredients": ["cánh gà", "mật ong", "tỏi", "rau củ nướng"],
    },
    {
        "name": "Cá hồi nướng chanh",
        "meal_type": "dinner",
        "calories": 380,
        "protein": 36,
        "carbs": 8,
        "fat": 22,
        "prep_time": 22,
        "difficulty": "easy",
        "tags": ["eat clean", "high protein", "keto", "low carb", "seafood"],
        "ingredients": ["cá hồi", "chanh", "dầu olive", "rau xanh"],
    },
    {
        "name": "Tôm nướng muối ớt",
        "meal_type": "dinner",
        "calories": 260,
        "protein": 32,
        "carbs": 6,
        "fat": 12,
        "prep_time": 18,
        "difficulty": "easy",
        "tags": ["eat clean", "high protein", "low carb", "quick", "seafood", "shellfish"],
        "ingredients": ["tôm sú", "muối ớt", "sả", "chanh"],
    },
    {
        "name": "Bò xào rau củ",
        "meal_type": "dinner",
        "calories": 400,
        "protein": 34,
        "carbs": 18,
        "fat": 20,
        "prep_time": 18,
        "difficulty": "easy",
        "tags": ["high protein", "low carb", "quick", "beef"],
        "ingredients": ["thịt bò", "bông cải", "ớt chuông", "tỏi"],
    },
    {
        "name": "Sườn nướng than",
        "meal_type": "dinner",
        "calories": 460,
        "protein": 32,
        "carbs": 20,
        "fat": 28,
        "prep_time": 30,
        "difficulty": "medium",
        "tags": ["high protein", "pork"],
        "ingredients": ["sườn heo", "ướp tỏi", "rau salad"],
    },
    {
        "name": "Cá lóc nướng giấy bạc",
        "meal_type": "dinner",
        "calories": 320,
        "protein": 36,
        "carbs": 4,
        "fat": 16,
        "prep_time": 30,
        "difficulty": "medium",
        "tags": ["vietnamese", "eat clean", "high protein", "low carb", "seafood"],
        "ingredients": ["cá lóc", "sả", "ớt", "nước mắm"],
    },
    {
        "name": "Lẩu nấm chay",
        "meal_type": "dinner",
        "calories": 280,
        "protein": 14,
        "carbs": 32,
        "fat": 10,
        "prep_time": 30,
        "difficulty": "easy",
        "tags": ["vegetarian", "vegan", "eat clean", "low carb"],
        "ingredients": ["nấm kim châm", "nấm hương", "cải thảo", "đậu phụ"],
    },
    {
        "name": "Lẩu gà lá é",
        "meal_type": "dinner",
        "calories": 360,
        "protein": 32,
        "carbs": 16,
        "fat": 16,
        "prep_time": 35,
        "difficulty": "medium",
        "tags": ["vietnamese", "high protein", "chicken"],
        "ingredients": ["gà ta", "lá é", "nấm", "bún"],
    },
    {
        "name": "Canh khổ qua nhồi thịt nạc",
        "meal_type": "dinner",
        "calories": 260,
        "protein": 22,
        "carbs": 12,
        "fat": 14,
        "prep_time": 35,
        "difficulty": "medium",
        "tags": ["vietnamese", "eat clean", "pork"],
        "ingredients": ["khổ qua", "thịt heo bằm", "nấm mèo"],
    },
    {
        "name": "Canh chua đậu bắp",
        "meal_type": "dinner",
        "calories": 180,
        "protein": 10,
        "carbs": 22,
        "fat": 6,
        "prep_time": 22,
        "difficulty": "easy",
        "tags": ["vegetarian", "vegan", "eat clean", "low carb"],
        "ingredients": ["đậu bắp", "cà chua", "dứa", "rau om"],
    },
    {
        "name": "Rau cải xào nấm",
        "meal_type": "dinner",
        "calories": 140,
        "protein": 6,
        "carbs": 16,
        "fat": 6,
        "prep_time": 12,
        "difficulty": "easy",
        "tags": ["vegetarian", "vegan", "eat clean", "quick", "low carb"],
        "ingredients": ["cải ngọt", "nấm", "tỏi"],
    },
    {
        "name": "Cà tím om thịt nạc",
        "meal_type": "dinner",
        "calories": 300,
        "protein": 24,
        "carbs": 16,
        "fat": 16,
        "prep_time": 30,
        "difficulty": "medium",
        "tags": ["vietnamese", "eat clean", "pork"],
        "ingredients": ["cà tím", "thịt heo bằm", "hành"],
    },
    {
        "name": "Đậu hũ nhồi nấm sốt cà",
        "meal_type": "dinner",
        "calories": 280,
        "protein": 20,
        "carbs": 14,
        "fat": 16,
        "prep_time": 25,
        "difficulty": "medium",
        "tags": ["vegetarian", "vegan", "eat clean", "low carb"],
        "ingredients": ["đậu hũ", "nấm", "cà chua"],
    },
    {
        "name": "Bò kho bánh mì (phần vừa)",
        "meal_type": "dinner",
        "calories": 480,
        "protein": 30,
        "carbs": 44,
        "fat": 18,
        "prep_time": 50,
        "difficulty": "medium",
        "tags": ["vietnamese", "high protein", "beef", "gluten"],
        "ingredients": ["thịt bò", "cà rốt", "bánh mì"],
    },
    {
        "name": "Gà hấp gừng",
        "meal_type": "dinner",
        "calories": 340,
        "protein": 40,
        "carbs": 6,
        "fat": 16,
        "prep_time": 30,
        "difficulty": "easy",
        "tags": ["eat clean", "high protein", "low carb", "gluten-free", "chicken"],
        "ingredients": ["gà ta", "gừng", "nấm", "hành"],
    },
    {
        "name": "Mực xào rau củ",
        "meal_type": "dinner",
        "calories": 280,
        "protein": 28,
        "carbs": 14,
        "fat": 12,
        "prep_time": 18,
        "difficulty": "easy",
        "tags": ["high protein", "low carb", "quick", "seafood"],
        "ingredients": ["mực", "cần tây", "cà rốt", "ớt"],
    },
    {
        "name": "Chả cá nướng rau",
        "meal_type": "dinner",
        "calories": 360,
        "protein": 30,
        "carbs": 20,
        "fat": 18,
        "prep_time": 28,
        "difficulty": "medium",
        "tags": ["vietnamese", "high protein", "seafood"],
        "ingredients": ["chả cá", "bún", "rau thìa là"],
    },
    {
        "name": "Nghêu hấp sả",
        "meal_type": "dinner",
        "calories": 200,
        "protein": 24,
        "carbs": 8,
        "fat": 6,
        "prep_time": 15,
        "difficulty": "easy",
        "tags": ["eat clean", "high protein", "low carb", "quick", "shellfish"],
        "ingredients": ["nghêu", "sả", "gừng", "ớt"],
    },
    {
        "name": "Salad tôm bơ",
        "meal_type": "dinner",
        "calories": 320,
        "protein": 28,
        "carbs": 14,
        "fat": 18,
        "prep_time": 15,
        "difficulty": "easy",
        "tags": ["eat clean", "high protein", "low carb", "keto", "quick", "seafood"],
        "ingredients": ["tôm", "bơ", "xà lách", "cà chua"],
    },
    {
        "name": "Cơm rang thập cẩm rau",
        "meal_type": "dinner",
        "calories": 400,
        "protein": 18,
        "carbs": 58,
        "fat": 12,
        "prep_time": 18,
        "difficulty": "easy",
        "tags": ["vietnamese", "quick"],
        "ingredients": ["cơm", "trứng", "ngô", "đậu Hà Lan"],
    },
    {
        "name": "Bún bò Huế (phần nhẹ)",
        "meal_type": "dinner",
        "calories": 440,
        "protein": 28,
        "carbs": 50,
        "fat": 14,
        "prep_time": 45,
        "difficulty": "hard",
        "tags": ["vietnamese", "high protein", "beef"],
        "ingredients": ["bún", "thịt bò", "chả", "rau"],
    },
    {
        "name": "Súp rau củ nấu gà",
        "meal_type": "dinner",
        "calories": 220,
        "protein": 20,
        "carbs": 18,
        "fat": 8,
        "prep_time": 25,
        "difficulty": "easy",
        "tags": ["eat clean", "gluten-free", "chicken"],
        "ingredients": ["gà", "khoai tây", "cà rốt", "bí đỏ"],
    },
    {
        "name": "Ức vịt quay chảo (phần nhỏ)",
        "meal_type": "dinner",
        "calories": 380,
        "protein": 32,
        "carbs": 8,
        "fat": 24,
        "prep_time": 35,
        "difficulty": "medium",
        "tags": ["high protein", "low carb"],
        "ingredients": ["ức vịt", "tỏi", "mật ong", "salad"],
    },
    {
        "name": "Cá basa hấp xì dầu",
        "meal_type": "dinner",
        "calories": 300,
        "protein": 34,
        "carbs": 6,
        "fat": 14,
        "prep_time": 20,
        "difficulty": "easy",
        "tags": ["eat clean", "high protein", "low carb", "seafood", "gluten-free"],
        "ingredients": ["cá basa", "xì dầu", "gừng", "hành"],
    },
    {
        "name": "Bí đỏ hấp tôm",
        "meal_type": "dinner",
        "calories": 240,
        "protein": 26,
        "carbs": 16,
        "fat": 8,
        "prep_time": 20,
        "difficulty": "easy",
        "tags": ["eat clean", "low carb", "seafood", "shellfish"],
        "ingredients": ["bí đỏ", "tôm", "hành", "tiêu"],
    },
    {
        "name": "Gỏi bắp cải tôm",
        "meal_type": "dinner",
        "calories": 220,
        "protein": 24,
        "carbs": 18,
        "fat": 6,
        "prep_time": 15,
        "difficulty": "easy",
        "tags": ["eat clean", "low carb", "quick", "seafood"],
        "ingredients": ["bắp cải", "tôm", "cà rốt", "rau thơm"],
    },
    {
        "name": "Đậu hũ sốt nấm",
        "meal_type": "dinner",
        "calories": 260,
        "protein": 18,
        "carbs": 12,
        "fat": 16,
        "prep_time": 18,
        "difficulty": "easy",
        "tags": ["vegetarian", "vegan", "eat clean", "low carb", "quick"],
        "ingredients": ["đậu hũ", "nấm", "tỏi", "hành lá"],
    },
    {
        "name": "Cháo tôm nấm",
        "meal_type": "dinner",
        "calories": 300,
        "protein": 22,
        "carbs": 40,
        "fat": 8,
        "prep_time": 25,
        "difficulty": "easy",
        "tags": ["eat clean", "seafood", "shellfish", "gluten-free"],
        "ingredients": ["gạo", "tôm", "nấm", "hành lá"],
    },
    {
        "name": "Bánh mì kẹp gà sốt yogurt",
        "meal_type": "dinner",
        "calories": 380,
        "protein": 30,
        "carbs": 40,
        "fat": 12,
        "prep_time": 15,
        "difficulty": "easy",
        "tags": ["eat clean", "high protein", "quick", "chicken", "gluten", "dairy"],
        "ingredients": ["bánh mì", "gà", "sữa chua", "rau"],
    },
    {
        "name": "Trứng chiên rau củ",
        "meal_type": "dinner",
        "calories": 280,
        "protein": 18,
        "carbs": 12,
        "fat": 18,
        "prep_time": 12,
        "difficulty": "easy",
        "tags": ["vegetarian", "quick", "low carb", "egg"],
        "ingredients": ["trứng", "cà rốt", "hành lá", "ớt"],
    },
    # ── Snack (10): ít đường, hỗ trợ theo dõi calories ──
    {
        "name": "Sinh tố xoài không đường",
        "meal_type": "snack",
        "calories": 160,
        "protein": 4,
        "carbs": 32,
        "fat": 2,
        "prep_time": 5,
        "difficulty": "easy",
        "tags": ["eat clean", "vegan", "quick", "low sugar"],
        "ingredients": ["xoài", "đá", "sữa hạnh nhân"],
    },
    {
        "name": "Sinh tố bơ cacao",
        "meal_type": "snack",
        "calories": 240,
        "protein": 6,
        "carbs": 18,
        "fat": 18,
        "prep_time": 5,
        "difficulty": "easy",
        "tags": ["eat clean", "keto", "quick", "low sugar"],
        "ingredients": ["bơ", "cacao", "sữa hạnh nhân"],
    },
    {
        "name": "Trái cây tô mix",
        "meal_type": "snack",
        "calories": 120,
        "protein": 2,
        "carbs": 28,
        "fat": 1,
        "prep_time": 5,
        "difficulty": "easy",
        "tags": ["vegan", "eat clean", "quick", "low sugar"],
        "ingredients": ["dưa hấu", "dứa", "nho", "dâu"],
    },
    {
        "name": "Hạnh nhân rang không muối",
        "meal_type": "snack",
        "calories": 180,
        "protein": 6,
        "carbs": 6,
        "fat": 15,
        "prep_time": 8,
        "difficulty": "easy",
        "tags": ["eat clean", "keto", "quick", "low carb"],
        "ingredients": ["hạnh nhân"],
    },
    {
        "name": "Sữa chua Hy Lạp mật ong",
        "meal_type": "snack",
        "calories": 160,
        "protein": 12,
        "carbs": 18,
        "fat": 4,
        "prep_time": 3,
        "difficulty": "easy",
        "tags": ["eat clean", "high protein", "quick", "low sugar", "dairy"],
        "ingredients": ["sữa chua Hy Lạp", "mật ong", "óc chó"],
    },
    {
        "name": "Chuối + bơ đậu phộng",
        "meal_type": "snack",
        "calories": 220,
        "protein": 8,
        "carbs": 26,
        "fat": 12,
        "prep_time": 3,
        "difficulty": "easy",
        "tags": ["eat clean", "quick", "peanut"],
        "ingredients": ["chuối", "bơ đậu phộng"],
    },
    {
        "name": "Chè đậu xanh ít đường",
        "meal_type": "snack",
        "calories": 180,
        "protein": 8,
        "carbs": 32,
        "fat": 2,
        "prep_time": 30,
        "difficulty": "easy",
        "tags": ["vietnamese", "vegetarian", "low sugar"],
        "ingredients": ["đậu xanh", "đường phèn", "dừa"],
    },
    {
        "name": "Chè khúc bạch lite",
        "meal_type": "snack",
        "calories": 220,
        "protein": 8,
        "carbs": 28,
        "fat": 8,
        "prep_time": 35,
        "difficulty": "medium",
        "tags": ["vietnamese", "low sugar", "dairy"],
        "ingredients": ["đậu hũ", "sữa tươi", "almond jelly"],
    },
    {
        "name": "Bánh flan ít đường",
        "meal_type": "snack",
        "calories": 150,
        "protein": 6,
        "carbs": 20,
        "fat": 5,
        "prep_time": 40,
        "difficulty": "medium",
        "tags": ["vietnamese", "low sugar", "egg", "dairy"],
        "ingredients": ["trứng", "sữa", "đường phèn"],
    },
    {
        "name": "Nước dừa tươi",
        "meal_type": "snack",
        "calories": 60,
        "protein": 1,
        "carbs": 12,
        "fat": 1,
        "prep_time": 2,
        "difficulty": "easy",
        "tags": ["vegan", "eat clean", "quick", "low sugar", "keto"],
        "ingredients": ["dừa tươi"],
    },
]


def slugify(name: str) -> str:
    s = unicodedata.normalize("NFD", name)
    s = "".join(c for c in s if unicodedata.category(c) != "Mn")
    s = s.lower().encode("ascii", "ignore").decode("ascii")
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s or "dish"


def enrich_tags(dish: dict) -> list[str]:
    """Keep manual tags; only auto-append quick for cooking_time filter."""
    tags = list(dict.fromkeys(t.lower().strip() for t in dish.get("tags", [])))
    if dish.get("prep_time", 30) <= 20 and "quick" not in tags:
        tags.append("quick")
    return tags


def description_for(dish: dict) -> str:
    name = dish["name"]
    meal = dish["meal_type"]
    prep = dish["prep_time"]
    cal = dish["calories"]
    meal_vi = {"breakfast": "sáng", "lunch": "trưa", "dinner": "tối", "snack": "phụ"}.get(meal, "")
    ingredients = dish.get("ingredients", [])
    ing_txt = ", ".join(ingredients[:5])
    if len(ingredients) > 5:
        ing_txt += "…"
    return (
        f"{name} — gợi ý Cravvy cho bữa {meal_vi}, ~{prep} phút, khoảng {cal} kcal. "
        f"Phù hợp người trẻ bận rộn, ăn lành và theo dõi dinh dưỡng tự động. "
        f"Nguyên liệu chính: {ing_txt}."
    )


def steps_for(dish: dict) -> list[str]:
    name = dish["name"]
    ingredients = dish.get("ingredients", [])
    ing = ", ".join(ingredients) if ingredients else "nguyên liệu tươi"
    meal = dish["meal_type"]

    if meal == "snack":
        return [
            f"Chuẩn bị: {ing}.",
            "Ưu tiên ít đường / portion vừa đủ (theo mục tiêu calories trong app).",
            "Trình bày và ghi nhận bữa phụ trong Cravvy để theo dõi tự động.",
        ]

    if any(k in name.lower() for k in ("gỏi", "salad", "bowl")):
        return [
            f"Rửa sạch và thái: {ing}.",
            "Chế biến protein (luộc/nướng) ít dầu, để nguội vừa phải.",
            "Trộn rau, sốt nhẹ (ít muối/đường), chia khẩu phần một người.",
            "Kiểm tra dị ứng đã khai báo trong hồ sơ Cravvy trước khi dùng.",
        ]

    if "cơm" in name.lower() or "gạo" in name.lower():
        return [
            f"Nấu cơm/gạo; chuẩn bị topping: {ing}.",
            "Protein nướng/luộc hoặc xào ít dầu.",
            "Xếp cơm + protein + rau, kiểm soát khẩu phần (~1 bát cơm).",
            "Ghi nhận bữa ăn trên Cravvy để cập nhật calories.",
        ]

    return [
        f"Chuẩn bị nguyên liệu: {ing}.",
        "Nấu theo công thức chuẩn Việt, hạn chế dầu mỡ và muối so với mức thông thường.",
        "Chia khẩu phần 1 người; ăn kèm rau xanh nếu có thể.",
        "Dùng trong meal plan hoặc đổi món nhanh (Meal Swap) trên Cravvy.",
    ]


def main() -> None:
    recipes = []
    seen_ids: set[str] = set()

    for dish in DISHES:
        meal_type = dish["meal_type"]
        tags = enrich_tags(dish)
        sid = slugify(dish["name"])
        if sid in seen_ids:
            sid = f"{sid}-{meal_type}"
        seen_ids.add(sid)

        recipes.append(
            {
                "name": dish["name"],
                "description": description_for({**dish, "tags": tags}),
                "image_url": None,
                "calories": dish["calories"],
                "protein": dish["protein"],
                "carbs": dish["carbs"],
                "fat": dish["fat"],
                "prep_time": dish["prep_time"],
                "difficulty": dish["difficulty"],
                "meal_type": meal_type,
                "tags": tags,
                "steps": steps_for(dish),
                "ingredients": dish.get("ingredients", []),
                "source": SOURCE,
                "source_id": sid,
                "locale": "vi",
                "is_active": True,
            }
        )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "version": 2,
        "project": "Cravvy Cooking App",
        "catalog_note": "Curated for eat-clean / urban 18-30, aligns with MVP meal plan + swap",
        "count": len(recipes),
        "recipes": recipes,
    }
    with OUT.open("w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)

    by_meal: dict[str, int] = {}
    for r in recipes:
        by_meal[r["meal_type"]] = by_meal.get(r["meal_type"], 0) + 1
    print(f"Wrote {len(recipes)} recipes to {OUT}")
    print("By meal_type:", by_meal)


if __name__ == "__main__":
    main()
